name: hello-world
on: push
jobs: 
  hello-world-job:
    #runner é engine que executa o job no workflow
    #Tem 2 tipos, github runner e self-hosted runner, self-hosted é um sistema que voce deployou e que cuida da infraestrutura dos jobs do Github Actions
    #-latest pega a ultima versão do sistema
    runs-on: ubuntu-latest
    steps:
        - name: check out repository code # nome do step
          uses: actions/checkout@v4 # usa o checkout no repositorio com a versao 4, se nao por a versao a ultima versao vai ser usada
        - run: echo "${cat hello_world.txt)" #printa o que ta no arquivo hello_world
        
    
